### ISSUE TITLE
Bug Search

### ISSUE THREAD

**Issue by heyner29** [enso-ui/select#10]
This is  a **bug**.

### Prerequisites
* [X] Are you running the latest version?
* [X] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [X] Did you check the documentation?
* [X] Did you perform a cursory search?

### Description
When several `$queryAttributes` are added, the component does not render them even if the backend responds well.
This is my select without search
![without search](https://user-images.githubusercontent.com/12703614/62628746-88026c00-b8f1-11e9-9b26-684fd52b6638.png)

This is my option controller
![option](https://user-images.githubusercontent.com/12703614/62628862-b718dd80-b8f1-11e9-8e9d-0670b8825b02.png)

### Actual behavior
When I perform the search by the `supplier.name` the component does not report results
![search](https://user-images.githubusercontent.com/12703614/62629297-808f9280-b8f2-11e9-9ba3-e99ab6fbd065.png)

`proandin` is the name of the `supplier`

**Comment by aocneanu** [comment]
This is happening because the frontend filters also the matching options, and your `label` does not contain the supplier. 

I just added a `disable-filtering` option for the FE component, but it would still be preferrable to add an accessor for this situation in your seller model:

```
public function getLabelAttribute() {
    return $this->first_name.' '.$this->last_name.' - '.$this->supplier->name;
}
```

don't forget to add the supplier to the `query()`

```
public function query() {
    return Seller::with('supplier');
}
```

and then set the FE components `:label="label"`.

This will ensure a working filter with option highlighting, won't be awkward for the user when you'll have two similar names on different suppliers and you'll search by name, and will avoid n+1 queries.

**Comment by heyner29** [comment]
Yes thank you, a similar approach had been done to achieve it.
In addition to your instructions you must use `protected $appends = ['fullName', 'label'];` in the model.
Once again, thank you very much for your help.
